"""nullable content postorm

Revision ID: 011f8888de41
Revises: 5f8791c27643
Create Date: 2026-08-25 23:51:48.560688

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "011f8888de41"
down_revision: Union[str, Sequence[str], None] = "5f8791c27643"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("posts_table", "content", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "posts_table", "content", existing_type=sa.VARCHAR(), nullable=False
    )
    # ### end Alembic commands ###
