"""user avatar key

Revision ID: 69a0f8090493
Revises: 011f8888de41
Create Date: 2026-09-28 22:04:50.499278

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "69a0f8090493"
down_revision: Union[str, Sequence[str], None] = "011f8888de41"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users_table", sa.Column("avatar_key", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users_table", "avatar_key")
    # ### end Alembic commands ###
