"""post deleting

Revision ID: 93e5c385169c
Revises: c328201a7bab
Create Date: 2026-08-15 21:19:41.207400

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "93e5c385169c"
down_revision: Union[str, Sequence[str], None] = "c328201a7bab"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("posts_table", sa.Column("is_deleted", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("posts_table", "is_deleted")
    # ### end Alembic commands ###
