"""post_author

Revision ID: c328201a7bab
Revises: f230844b2633
Create Date: 2026-08-15 18:41:47.312379

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "c328201a7bab"
down_revision: Union[str, Sequence[str], None] = "f230844b2633"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("posts_table", sa.Column("author_id", sa.Integer(), nullable=False))
    op.create_foreign_key(None, "posts_table", "users_table", ["author_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "posts_table", type_="foreignkey")
    op.drop_column("posts_table", "author_id")
    # ### end Alembic commands ###
